apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe
  labels:
    app: tictactoe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
      - name: tictactoe
        image: docker.io/boluex/tictactoe:master-3ea81af
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 80        


---
apiVersion: v1
kind: Service 
metadata:
  name: tictactoe
spec:
  selector:
    app: tictactoe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP