name: tictactore cicd

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'kubernetes/deployment.yaml'
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test || echo "Tests not found"

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: npm install

    - name: build project
      run: npm run build

    - name: build Production Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist/


    - name: Build and Push Docker Image 
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ${{ secrets.DOCKER_USERNAME }}/tictactoe
        registry: docker.io
        tags: 1.0
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}